### PR TITLE
Add support for rustls as TLS backend

### PR DESCRIPTION
**Pull request by dnaka91**
This adds support for `rustls` as alternative to `native-tls` and can be enabled with either `transport-tcp-rustls` or `transport-wss-rustls`. If one of these is enabled together with the native-tls version, then native-tls is used instead. For example, using `transport-tcp` AND `transport-tcp-rustls` results in using `native-tls` for the TLS connections.

The only new dependencies are `tokio-rustls` and `webpki-roots` but I sorted the imports causing a bigger diff.

In addition, I changed the default to `rustls` but if you prefer `native-tls` staying the default I will change back that part of course 🙇‍♂️.

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

### CODE REVIEW

**Comment by RAnders00** [comment]
Thank you a lot for putting work into these improvements. Since this is a bit of a bigger change I'll review it properly on the upcoming weekend, just thought I'd not leave you hanging.

**Review by RAnders00 — CHANGES_REQUESTED** [review]
I think I want to support native certstores in addition to just webpki-roots (for rustls), do you think you can make that work?

Also, I'm happy to make major version bumps, I think it might be better if the existing `transport-tcp` was renamed `transport-tcp-native-tls` or similar.

Then also, the `lib.rs` documentation needs updating to list the new feature flags.

**Comment by dnaka91** [comment]
Thanks for reviewing.

That shouldn't be a big problem as there's a `rustls-native-certs` crate just for that.

I look into it tomorrow and will make a few changes.

**Comment by dnaka91** [comment]
@RAnders00 I added the `rustls-native-certs` dependency which is now a feature at the same time. So by enabling `transport-tcp-rustls` and `rustls-native-certs`, it will switch to the native certs. 

The `webpki-roots` would still be included in that case but I felt it being too much having `transport-tcp-rustls-webpki-roots` and `transport-tcp-rustls-native-certs`. Also, the `webpki-roots` crates has no dependencies besides `webpki` which is needed anyways.

**Comment by RAnders00** [comment]
@dnaka91 based on this PR I created a new, bigger PR: #113 I'll leave my own PR up for a few days for others to have a look, if you've got time and if you're interested I would appreciate if you could take a look at my proposed implementation! It adds Rustls support as well as support for plain-text connections, which I wanted to do "in one go" since they both would introduce potentially breaking changes and work for library users. I've decided to go with a breaking change and make the new names of the structs and feature flags as consistent and intutive as possible. If you read the new `lib.rs` documentation and `CHANGELOG.md` on the linked PR I tried to lay out what the changes are. Thanks!

**Comment by dnaka91** [comment]
@RAnders00 I'm curious what the use case for a plain connection is as it's quite a security risk 🤔

**Comment by RAnders00** [comment]
Plain connections could be useful for environments that need smaller binary sizes (embedded), when the use-case is to join chat anonymously. Since this is a library it feels wrong to me to be opinionated about the way that users should connect to chat.

**Comment by dnaka91** [comment]
Hey @RAnders00 I guess we're going with your version of this change then.

Just a few notes about plain connections and embedded devices:
- Support for embedded devices is rather unlikely as this crate and many dependencies don't support `no_std` and rely on `TlsStream` whereas on embedded devices you have neither the stlib nor the standard TlsStream.
- If there is a plain connection version, at least all login/auth related functions should be stripped to avoid misuse (mostly exposing credentials over plain connections).
- Having plain connections is probably YAGNI (You ain't gonna need it). Just because Twitch proides a non-TLS connection, doesn't necessarily mean it should be used.

That's just my opinion regarding the topic. After all it's your crate, so I'm not to tell you what to do with it and can just give suggestions. Most important for me is that `rustls` is added so I don't have to have **rustls + native-tls** in my project.

**Comment by RAnders00** [comment]
I guess that is a reasonable idea - force the library user to use anonymous connections if they are going to use un-encrypted connections. Thanks for the suggestion!

And of course, thank you as well for your initial rustls support implementation - I ended up borrowing lots of code snippets from your implementation. Your help is much appreciated.

**Comment by dnaka91** [comment]
Just want to say many thanks for this crate btw. I use it for a small twitch & discord bot and especially the automatic reconnect is just great 👍

**Pull request closed without merging**
